package xmodelbin

import (
	"bytes"
	"encoding/binary"
	"reflect"
	"testing"
)

// literalBlock encodes data as one LZ4 sequence of literals only: valid LZ4,
// enough to build test files.
func literalBlock(data []byte) []byte {
	var b bytes.Buffer
	if len(data) < 15 {
		b.WriteByte(byte(len(data) << 4))
	} else {
		b.WriteByte(0xF0)
		for rest := len(data) - 15; ; rest -= 255 {
			if rest < 255 {
				b.WriteByte(byte(rest))
				break
			}
			b.WriteByte(255)
		}
	}
	b.Write(data)
	return b.Bytes()
}

func bin(stream []byte) []byte {
	out := []byte("*LZ4*")
	out = binary.LittleEndian.AppendUint32(out, uint32(len(stream)))
	return append(out, literalBlock(stream)...)
}

// token stream helpers: a 16-bit id and a 16-bit value in one aligned word,
// strings NUL-terminated and padded to 4 bytes.
func word(id, v uint16) []byte {
	return binary.LittleEndian.AppendUint16(binary.LittleEndian.AppendUint16(nil, id), v)
}

func str(s string) []byte {
	b := append([]byte(s), 0)
	for len(b)%4 != 0 {
		b = append(b, 0)
	}
	return b
}

func stream(parts ...[]byte) []byte { return bytes.Join(parts, nil) }

func TestMaterialsBinary(t *testing.T) {
	s := stream(
		word(0xC355, 0), str("Generated by a test"),
		word(0x76BA, 1), word(0xF099, 0), str("tag_origin"), // NUMBONES 1, BONE "tag_origin"
		word(0xA1B2, 9), // a decoy NUMMATERIALS: no MATERIAL entries follow it
		word(0x62AF, 2), word(0x87D4, 0), str("mesh_0"), word(0x87D4, 1), str("mesh_1"),
		word(0xA1B2, 2),
		word(0xA700, 0), str("mtl_body"), str("Phong"), str("Phong"),
		[]byte{0, 0, 0x80, 0x3f}, word(0x1234, 0), // a property between materials
		word(0xA700, 1), str("mtl_glass"), str("Phong"), str("Phong"),
	)
	got, err := Materials(bin(s))
	if err != nil {
		t.Fatal(err)
	}
	if want := []string{"mtl_body", "mtl_glass"}; !reflect.DeepEqual(got, want) {
		t.Errorf("got %q, want %q", got, want)
	}

	// the count can sit in the very last word of the stream
	got, err = Materials(bin(stream(word(0xC355, 0), str("x"), word(0xA1B2, 0))))
	if err != nil || len(got) != 0 {
		t.Errorf("a model with no material: %q, %v", got, err)
	}
}

func TestMaterialsText(t *testing.T) {
	exp := "// exported\nMODEL\nVERSION 6\nNUMMATERIALS 2\nMATERIAL 0 \"mtl_a\" \"Phong\" \"Phong\"\nCOLOR 0 0 0 1\nMATERIAL 1 \"mtl_b\" \"Phong\" \"Phong\"\n"
	for name, b := range map[string][]byte{"plain": []byte(exp), "lz4": bin([]byte(exp))} {
		got, err := Materials(b)
		if err != nil || !reflect.DeepEqual(got, []string{"mtl_a", "mtl_b"}) {
			t.Errorf("%s: %q, %v", name, got, err)
		}
	}
}

func TestCorrupt(t *testing.T) {
	for name, b := range map[string][]byte{
		"truncated header": []byte("*LZ4*\x01"),
		"size mismatch":    append([]byte("*LZ4*\x10\x00\x00\x00"), literalBlock([]byte("abc"))...),
		"bad offset":       append([]byte("*LZ4*\x09\x00\x00\x00"), 0x32, 'a', 'b', 'c', 9, 0),
		"absurd size":      []byte("*LZ4*\xff\xff\xff\xff\x00"),
		"no materials":     bin(stream(word(0xC355, 0), str("x"))),
	} {
		if _, err := Materials(b); err == nil {
			t.Errorf("%s: want an error", name)
		}
	}
}

func FuzzMaterials(f *testing.F) {
	f.Add(bin(stream(word(0xA1B2, 1), word(0xA700, 0), str("mtl"))))
	f.Add([]byte("MATERIAL 0 \"a\""))
	f.Add([]byte("*LZ4*\x09\x00\x00\x00\x32abc\x03\x00"))
	f.Fuzz(func(t *testing.T, b []byte) {
		_, _ = Materials(b) // must not panic on any input
	})
}
